name: CD - Build Windows

on:
  workflow_call:
    inputs:
      display_version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      ASSET_NAME_WIN_X64:
        required: true
        type: string
      ASSET_NAME_WIN_X86:
        required: true
        type: string
      ASSET_NAME_WIN_X64_SELF_CONTAINED:
        required: true
        type: string
      ASSET_NAME_WIN_X86_SELF_CONTAINED:
        required: true
        type: string
      CSPROJ_PATH:
        required: true
        type: string
      OUTPUT_DIR:
        required: true
        type: string
      SDK_VERSION:
        required: true
        type: string
      TARGET_FRAMEWORK_WIN:
        required: true
        type: string
      TARGET_RUNTIME_WINX64:
        required: true
        type: string
      TARGET_RUNTIME_WINX86:
        required: true
        type: string
      THIRD_PARTY_LICENSE_INFO_DIR:
        required: true
        type: string
      THIRD_PARTY_LICENSE_LIST_NAME:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    env:
      WITHOUT_ANDROID: true

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.SDK_VERSION }}
      - name: Install dotnet workloads
        run: dotnet workload install maui-windows

      - name: Install dependencies
        run: dotnet restore ${{ inputs.CSPROJ_PATH }}

      - name: Dump third-party license info
        uses: ./.github/actions/dump-third-party-licenses
        with:
          platform: windows
          license-info-dir: ${{ inputs.THIRD_PARTY_LICENSE_INFO_DIR }}
          license-list-name: ${{ inputs.THIRD_PARTY_LICENSE_LIST_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build x64
        run: >
          dotnet publish ${{ inputs.CSPROJ_PATH }}
          -f ${{ inputs.TARGET_FRAMEWORK_WIN }}
          -c Release
          -o "${{ inputs.OUTPUT_DIR }}"
          /p:WindowsPackageType=None
          /p:RuntimeIdentifierOverride=${{ inputs.TARGET_RUNTIME_WINX64 }}
          /p:ApplicationDisplayVersion=${{ inputs.display_version }}
          /p:ApplicationVersion=${{ inputs.build_number }}

      - name: Upload x64
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.ASSET_NAME_WIN_X64 }}
          path: ${{ inputs.OUTPUT_DIR }}
          retention-days: 3

      - name: Clear Output Directory
        run: Remove-Item -Recurse -Force -Path ${{ inputs.OUTPUT_DIR }}

      - name: Build x64 Self Contained
        run: >
          dotnet publish ${{ inputs.CSPROJ_PATH }}
          -f ${{ inputs.TARGET_FRAMEWORK_WIN }}
          -c Release
          -o "${{ inputs.OUTPUT_DIR }}"
          /p:WindowsPackageType=None
          /p:WindowsAppSDKSelfContained=true
          --self-contained
          /p:RuntimeIdentifierOverride=${{ inputs.TARGET_RUNTIME_WINX64 }}
          /p:ApplicationDisplayVersion=${{ inputs.display_version }}
          /p:ApplicationVersion=${{ inputs.build_number }}

      - name: Upload x64 Self Contained
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.ASSET_NAME_WIN_X64_SELF_CONTAINED }}
          path: ${{ inputs.OUTPUT_DIR }}
          retention-days: 3

      - name: Clear Output Directory
        run: Remove-Item -Recurse -Force -Path ${{ inputs.OUTPUT_DIR }}

      - name: Build x86
        run: >
          dotnet publish ${{ inputs.CSPROJ_PATH }}
          -f ${{ inputs.TARGET_FRAMEWORK_WIN }}
          -c Release
          -o "${{ inputs.OUTPUT_DIR }}"
          /p:WindowsPackageType=None
          /p:RuntimeIdentifierOverride=${{ inputs.TARGET_RUNTIME_WINX86 }}
          /p:ApplicationDisplayVersion=${{ inputs.display_version }}
          /p:ApplicationVersion=${{ inputs.build_number }}

      - name: Upload x86
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.ASSET_NAME_WIN_X86 }}
          path: ${{ inputs.OUTPUT_DIR }}
          retention-days: 3

      - name: Clear Output Directory
        run: Remove-Item -Recurse -Force -Path ${{ inputs.OUTPUT_DIR }}

      - name: Build x86 Self Contained
        run: >
          dotnet publish ${{ inputs.CSPROJ_PATH }}
          -f ${{ inputs.TARGET_FRAMEWORK_WIN }}
          -c Release
          -o "${{ inputs.OUTPUT_DIR }}"
          /p:WindowsPackageType=None
          /p:WindowsAppSDKSelfContained=true
          --self-contained
          /p:RuntimeIdentifierOverride=${{ inputs.TARGET_RUNTIME_WINX86 }}
          /p:ApplicationDisplayVersion=${{ inputs.display_version }}
          /p:ApplicationVersion=${{ inputs.build_number }}

      - name: Upload x86 Self Contained
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.ASSET_NAME_WIN_X86_SELF_CONTAINED }}
          path: ${{ inputs.OUTPUT_DIR }}
          retention-days: 3
