name: CD - Build Android

on:
  workflow_call:
    inputs:
      display_version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      AAB_PATH:
        required: true
        type: string
      APK_PATH:
        required: true
        type: string
      CSPROJ_PATH:
        required: true
        type: string
      OUTPUT_DIR:
        required: true
        type: string
      SDK_VERSION:
        required: true
        type: string
      TARGET_FRAMEWORK_ANDROID:
        required: true
        type: string
      THIRD_PARTY_LICENSE_INFO_DIR:
        required: true
        type: string
      THIRD_PARTY_LICENSE_LIST_NAME:
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.SDK_VERSION }}
      - name: Install dotnet workloads
        run: dotnet workload install maui-android

      - name: Install dependencies
        run: dotnet restore ${{ inputs.CSPROJ_PATH }}

      - name: Dump third-party license info
        uses: ./.github/actions/dump-third-party-licenses
        with:
          platform: android
          license-info-dir: ${{ inputs.THIRD_PARTY_LICENSE_INFO_DIR }}
          license-list-name: ${{ inputs.THIRD_PARTY_LICENSE_LIST_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Google-services.json
        env:
          FIREBASE_ANDROID_JSON: ${{ secrets.FIREBASE_ANDROID_JSON }}
        run: |
          echo "$FIREBASE_ANDROID_JSON" > TRViS/Google-services.json
          ls -l TRViS/Google-services.json

      # ref: https://github.com/actions/runner-images/issues/8952#issuecomment-1886084791
      - name: Install Android SDK Platform Tools
        run: >
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
          --sdk_root="$ANDROID_SDK_ROOT"
          "platform-tools"
      - name: Create Android Signing Key
        run: echo "${{ secrets.ANDROID_SIGNING_KEY_STORE }}" | base64 --decode > '${{ github.workspace }}/keystore.jks'
      - name: Build
        run: >
          dotnet publish ${{ inputs.CSPROJ_PATH }}
          -f ${{ inputs.TARGET_FRAMEWORK_ANDROID }}
          -c Release
          -o "${{ inputs.OUTPUT_DIR }}"
          /p:ApplicationDisplayVersion=${{ inputs.display_version }}
          /p:ApplicationVersion=${{ inputs.build_number }}
          /p:AndroidKeyStore=true
          /p:AndroidSigningKeyAlias='${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}'
          /p:AndroidSigningKeyPass='${{ secrets.ANDROID_SIGNING_KEY_PASS }}'
          /p:AndroidSigningKeyStore='${{ github.workspace }}/keystore.jks'
          /p:AndroidSigningStorePass='${{ secrets.ANDROID_SIGNING_KEY_STORE_PASS }}'

      - name: Upload AAB
        uses: actions/upload-artifact@v7
        with:
          name: aab
          path: ${{ inputs.AAB_PATH }}
          retention-days: 3

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: apk
          path: ${{ inputs.APK_PATH }}
          retention-days: 3
