name: Continuous Delivery Action

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-.[0-9]+"
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., 1.2.3)"
        required: false
        type: string

concurrency: cd-action-${{ github.ref }}

env:
  CSPROJ_PATH: ./TRViS/TRViS.csproj

jobs:
  generate-bundle-version:
    if: |
      !startsWith(github.ref, 'refs/tags/v')
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
      && !cancelled()

    runs-on: ubuntu-slim
    timeout-minutes: 5

    outputs:
      display_version: ${{ steps.set_display_version.outputs.disp-version }}
      build_number: ${{ steps.build_number.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'push' && github.head_ref || github.event_name == 'pull_request' && github.head_ref || '' }}

      - name: Get all tags from remote
        run: git fetch --all --tags

      - name: generate bundle version pattern (Trigger:Push to main)
        if: ${{ github.event_name == 'push' }}
        run: grep -oP '(?<=<ApplicationDisplayVersion>).*?(?=</ApplicationDisplayVersion>)' ${{ env.CSPROJ_PATH }} > DISP_VERSION

      - name: generate bundle version pattern (Trigger:PullRequest)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "0.0.${{ github.event.number }}" > DISP_VERSION

      - name: generate bundle version pattern (Trigger:WorkflowDispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "${{ github.event.inputs.version }}" > DISP_VERSION
          else
            echo "0.0.0" > DISP_VERSION
          fi

      - name: set display version to variable
        id: set_display_version
        run: |
          echo "disp-version=$(cat DISP_VERSION)" >> $GITHUB_OUTPUT

      - name: Get all tags reachable from current commit
        run: |
          git tag -l "v${{ steps.set_display_version.outputs.disp-version }}-[0-9]*" > VERSION_TAGS
          cat VERSION_TAGS

      - name: Generate new patch build number
        id: build_number
        run: |
          if [ `cat VERSION_TAGS | wc -l` -eq 0 ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=`sort -rV VERSION_TAGS | head -n 1 | awk -F '-' '{print $2 + 1}'`
          fi
          echo "version=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: print new version number
        run: echo "VersionNumber ... ${{ steps.set_display_version.outputs.disp-version }}-${{ steps.build_number.outputs.version }}"

  get-version:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    runs-on: ubuntu-slim
    timeout-minutes: 2
    needs:
      - generate-bundle-version
    outputs:
      display_version: ${{ steps.get-version.outputs.display_version }}
      build_number: ${{ steps.get-version.outputs.build_number }}

    steps:
      - name: get version
        id: get-version
        run: |
          if [ '${{ startsWith(github.ref, 'refs/tags/v') }}' == 'true' ]; then
            VERSION=`echo '${{ github.ref }}' | tr -d 'refs/tags/v'`
            echo "display_version=$(echo $VERSION | awk -F '-' '{print $1}')" >> $GITHUB_OUTPUT
            echo "build_number=$(echo $VERSION | awk -F '-' '{print $2}')" >> $GITHUB_OUTPUT
          else
            echo "display_version=${{ needs.generate-bundle-version.outputs.display_version }}" >> $GITHUB_OUTPUT
            echo "build_number=${{ needs.generate-bundle-version.outputs.build_number }}" >> $GITHUB_OUTPUT
          fi

  build-ios:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - get-version
    runs-on: macos-26
    timeout-minutes: 30
    env:
      WITHOUT_ANDROID: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-build-ios
        with:
          display_version: ${{ needs.get-version.outputs.display_version }}
          build_number: ${{ needs.get-version.outputs.build_number }}
          CSPROJ_PATH: ./TRViS/TRViS.csproj
          IOS_DSYM_FILENAME: TRViS.app.dSYM
          IOS_DSYM_PATH: ./TRViS/bin/Release/net10.0-ios/ios-arm64
          IPA_PATH: ./out/TRViS.ipa
          OUTPUT_DIR: ./out
          SDK_VERSION: "10.0.x"
          TARGET_FRAMEWORK: net10.0-ios
          TARGET_RUNTIME: ios-arm64
          THIRD_PARTY_LICENSE_INFO_DIR: ./TRViS/Resources/Raw/licenses
          THIRD_PARTY_LICENSE_LIST_NAME: license_list
          XCODE_VERSION: "26.4"
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          P12_FILE_BASE64: ${{ secrets.P12_FILE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_IOS_PLIST: ${{ secrets.FIREBASE_IOS_PLIST }}
          CODESIGN_KEY_NAME_IOS: ${{ secrets.CODESIGN_KEY_NAME_IOS }}
          CODESIGN_PROVISION_NAME_IOS: ${{ secrets.CODESIGN_PROVISION_NAME_IOS }}

  build-android:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - get-version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-build-android
        with:
          display_version: ${{ needs.get-version.outputs.display_version }}
          build_number: ${{ needs.get-version.outputs.build_number }}
          AAB_PATH: ./out/dev.t0r.trvis-Signed.aab
          APK_PATH: ./out/dev.t0r.trvis-Signed.apk
          CSPROJ_PATH: ./TRViS/TRViS.csproj
          OUTPUT_DIR: ./out
          SDK_VERSION: "10.0.x"
          TARGET_FRAMEWORK_ANDROID: net10.0-android
          THIRD_PARTY_LICENSE_INFO_DIR: ./TRViS/Resources/Raw/licenses
          THIRD_PARTY_LICENSE_LIST_NAME: license_list
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_ANDROID_JSON: ${{ secrets.FIREBASE_ANDROID_JSON }}
          ANDROID_SIGNING_KEY_STORE: ${{ secrets.ANDROID_SIGNING_KEY_STORE }}
          ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          ANDROID_SIGNING_KEY_PASS: ${{ secrets.ANDROID_SIGNING_KEY_PASS }}
          ANDROID_SIGNING_KEY_STORE_PASS: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASS }}

  build-mac:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - get-version
    runs-on: macos-26
    timeout-minutes: 30
    env:
      WITHOUT_ANDROID: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-build-mac
        with:
          display_version: ${{ needs.get-version.outputs.display_version }}
          build_number: ${{ needs.get-version.outputs.build_number }}
          CSPROJ_PATH: ./TRViS/TRViS.csproj
          OUTPUT_DIR: ./out
          PKG_PATH: ./out/TRViS.pkg
          SDK_VERSION: "10.0.x"
          TARGET_FRAMEWORK_MAC: net10.0-maccatalyst
          TARGET_RUNTIME_MAC: osx
          THIRD_PARTY_LICENSE_INFO_DIR: ./TRViS/Resources/Raw/licenses
          THIRD_PARTY_LICENSE_LIST_NAME: license_list
          XCODE_VERSION: "26.4"
          PROVISIONING_PROFILE_MAC: ${{ secrets.PROVISIONING_PROFILE_MAC }}
          P12_FILE_MAC_BASE64: ${{ secrets.P12_FILE_MAC_BASE64 }}
          P12_PASSWORD_MAC: ${{ secrets.P12_PASSWORD_MAC }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODESIGN_KEY_NAME_MAC: ${{ secrets.CODESIGN_KEY_NAME_MAC }}
          CODESIGN_PROVISION_NAME_MAC: ${{ secrets.CODESIGN_PROVISION_NAME_MAC }}
          PACKAGE_SIGN_KEY_NAME_MAC: ${{ secrets.PACKAGE_SIGN_KEY_NAME_MAC }}

  build-windows:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - get-version
    runs-on: windows-latest
    timeout-minutes: 30
    env:
      WITHOUT_ANDROID: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-build-windows
        with:
          display_version: ${{ needs.get-version.outputs.display_version }}
          build_number: ${{ needs.get-version.outputs.build_number }}
          ASSET_NAME_WIN_X64: TRViS-win-x64
          ASSET_NAME_WIN_X86: TRViS-win-x86
          ASSET_NAME_WIN_X64_SELF_CONTAINED: TRViS-win-x64-self-contained
          ASSET_NAME_WIN_X86_SELF_CONTAINED: TRViS-win-x86-self-contained
          CSPROJ_PATH: ./TRViS/TRViS.csproj
          OUTPUT_DIR: ./out
          SDK_VERSION: "10.0.x"
          TARGET_FRAMEWORK_WIN: net10.0-windows10.0.19041.0
          TARGET_RUNTIME_WINX64: win-x64
          TARGET_RUNTIME_WINX86: win-x86
          THIRD_PARTY_LICENSE_INFO_DIR: ./TRViS/Resources/Raw/licenses
          THIRD_PARTY_LICENSE_LIST_NAME: license_list
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-ios:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - build-ios
    runs-on: macos-26
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-publish-appstore
        with:
          platform: ios
          artifact_name: ipa
          IPA_PATH: ./out/TRViS.ipa
          OUTPUT_DIR: ./out
          PKG_PATH: ./out/TRViS.pkg
          APPSTORECONNECT_API_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_API_PRIVATE_KEY }}
          APPSTORECONNECT_API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
          APPSTORECONNECT_ISSUER_ID: ${{ secrets.APPSTORECONNECT_ISSUER_ID }}

  publish-mac:
    if: |
      !failure()
      && !cancelled()
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.draft == false
      )
    needs:
      - build-mac
    runs-on: macos-26
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-publish-appstore
        with:
          platform: mac
          artifact_name: pkg
          IPA_PATH: ./out/TRViS.ipa
          OUTPUT_DIR: ./out
          PKG_PATH: ./out/TRViS.pkg
          APPSTORECONNECT_API_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_API_PRIVATE_KEY }}
          APPSTORECONNECT_API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
          APPSTORECONNECT_ISSUER_ID: ${{ secrets.APPSTORECONNECT_ISSUER_ID }}

  set-tag-ios:
    if: |
      needs.generate-bundle-version.result == 'success'
      && needs.publish-ios.result == 'success'
      && (
        github.event_name != 'workflow_dispatch'
        || github.event.inputs.version != ''
      )
    needs:
      - generate-bundle-version
      - publish-ios
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-set-tag
        with:
          display_version: ${{ needs.generate-bundle-version.outputs.display_version }}
          build_number: ${{ needs.generate-bundle-version.outputs.build_number }}

  set-tag-mac:
    if: |
      needs.generate-bundle-version.result == 'success'
      && needs.publish-mac.result == 'success'
      && (
        github.event_name != 'workflow_dispatch'
        || github.event.inputs.version != ''
      )
    needs:
      - generate-bundle-version
      - publish-mac
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-set-tag
        with:
          display_version: ${{ needs.generate-bundle-version.outputs.display_version }}
          build_number: ${{ needs.generate-bundle-version.outputs.build_number }}

  set-tag-android:
    if: |
      needs.generate-bundle-version.result == 'success'
      && needs.build-android.result == 'success'
      && (
        github.event_name != 'workflow_dispatch'
        || github.event.inputs.version != ''
      )
    needs:
      - generate-bundle-version
      - build-android
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-set-tag
        with:
          display_version: ${{ needs.generate-bundle-version.outputs.display_version }}
          build_number: ${{ needs.generate-bundle-version.outputs.build_number }}

  set-tag-windows:
    if: |
      needs.generate-bundle-version.result == 'success'
      && needs.build-windows.result == 'success'
      && (
        github.event_name != 'workflow_dispatch'
        || github.event.inputs.version != ''
      )
    needs:
      - generate-bundle-version
      - build-windows
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-set-tag
        with:
          display_version: ${{ needs.generate-bundle-version.outputs.display_version }}
          build_number: ${{ needs.generate-bundle-version.outputs.build_number }}

  comment-pr:
    if: |
      always()
      && github.event_name == 'pull_request'
      && (
        needs.set-tag-ios.result == 'success'
        || needs.set-tag-mac.result == 'success'
        || needs.set-tag-android.result == 'success'
        || needs.set-tag-windows.result == 'success'
      )
    runs-on: ubuntu-slim
    timeout-minutes: 5
    needs:
      - generate-bundle-version
      - set-tag-ios
      - set-tag-mac
      - set-tag-android
      - set-tag-windows
    steps:
      - name: Comment TagName and Actions-Run URL to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Tag `v${{ needs.generate-bundle-version.outputs.display_version }}-${{ needs.generate-bundle-version.outputs.build_number }}` was automatically created and pushed with ... https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} (Platform Status iOS: ${{ needs.set-tag-ios.result }} / macOS: ${{ needs.set-tag-mac.result }} / Android: ${{ needs.set-tag-android.result }} / Windows: ${{ needs.set-tag-windows.result }})' | gh pr comment ${{ github.event.number }} -F - --repo ${{ github.repository }}

  create-release:
    if: |
      always()
      && (
        needs.set-tag-ios.result == 'success'
        || needs.set-tag-mac.result == 'success'
        || needs.set-tag-android.result == 'success'
        || needs.set-tag-windows.result == 'success'
      )
      && (
        (
          github.event_name == 'push'
          && github.ref_name == 'main'
        )
        || (
          github.event_name == 'workflow_dispatch'
          && github.event.inputs.version != ''
        )
      )
    needs:
      - generate-bundle-version
      - set-tag-ios
      - set-tag-mac
      - set-tag-android
      - set-tag-windows
      - build-android
      - build-windows
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cd-create-release
        with:
          tag_name: v${{ needs.generate-bundle-version.outputs.display_version }}-${{ needs.generate-bundle-version.outputs.build_number }}
          ASSET_NAME_WIN_X64: TRViS-win-x64
          ASSET_NAME_WIN_X86: TRViS-win-x86
          ASSET_NAME_WIN_X64_SELF_CONTAINED: TRViS-win-x64-self-contained
          ASSET_NAME_WIN_X86_SELF_CONTAINED: TRViS-win-x86-self-contained
          OUTPUT_DIR: ./out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
